### ISSUE TITLE
debug source mapping

### ISSUE THREAD

**Issue by generalhenry** [atomiqio/atomiq-cli#7]
currently `atomiq debug` works sans mapping.

https://www.npmjs.com/package/babel-node-debug looks hopeful

**Comment by subfuzion** [comment]
It was working before when we were using the yeoman generator. It seems like something broke when I switched to using the babel api.

**Comment by subfuzion** [comment]
It's possible that this is where I broke it: https://github.com/atomiqio/atomiq-cli/blob/master/src/lib/BabelHelper.js#L32

The sourcemap output might be off just a bit. I sort of just winged this part when I was trying to get it out the door last month.

**Comment by subfuzion** [comment]
@jdavanne fixed this for me (https://github.com/atomiqio/atomiq-cli/pull/27). 👍
