### ISSUE TITLE
lint and format

### ISSUE THREAD

**Issue by generalhenry** [atomiqio/atomiq-cli#9]
I've added linting and formatting to the projects but it should be moved to `atomiq lint` and `atomiq format` since atomiq-cli already has the dependencies

**Comment by subfuzion** [comment]
Regarding the commands, I guess we need to make a decision about what lives at the top level of the command structure and what the sub commands are. For example, all the things that involve building are subcommands under `atomiq make`.

**Comment by subfuzion** [comment]
We will use commands as proposed by @generalhenry.
